### ISSUE TITLE
入力フォームの修正（contact）

### ISSUE THREAD

**Issue by Taka-hyt** [Kuma-inataku/tenkue-app-r005#10]
@Kuma-inataku 
contactページの入力フォームの背景色がデザインデータと大きく異なっています。
修正をお願いします。
<img width="1220" alt="スクリーンショット 2020-10-25 20 25 27" src="https://user-images.githubusercontent.com/53964838/97105731-94463500-1700-11eb-9368-46b0a4bd809c.png">

**Comment by Kuma-inataku** [comment]
こちらについては修正しました
ただ、ブラウザ上で問題ないか確認すべきですが、slack上で質問させていただいている通りブラウザ上での表示の仕方がわかっていないため、こちらでブラウザでの確認ができましたらご連絡いたします！

**Comment by Kuma-inataku** [comment]
あらかじめ用意いただいたscss内の_base.scssを使い、$color-primary: #00478b;から$color-gold: #e8e1d3;、$color-light: #fff;に変更しました。

**Comment by Taka-hyt** [comment]
修正されたことを確認しました。
