### ISSUE TITLE
ACCESSのメインビジュアルの画像がCONTACTの画像になっている

### ISSUE THREAD

**Issue by Taka-hyt** [Kuma-inataku/tenkue-app-r005#11]
@Kuma-inataku 
表題の通り、ACCESSのメインビジュアルの画像がCONTACTのと同じものが表示されていますので修正お願いします。

**Comment by Kuma-inataku** [comment]
お疲れ様です。
こちらについてはnpm run startしたブラウザを確認し、サンプル通りで画像が表示されていることを確認しました。
ご確認のほどよろしくお願いいたします。
