### ISSUE TITLE
CSSの修正（ACCESS）

### ISSUE THREAD

**Issue by Taka-hyt** [Kuma-inataku/tenkue-app-r005#12]
@Kuma-inataku 
HTMLタグに直接スタイルを当てている箇所がありますが、このままで良いでしょうか？
`<body>``<header>``<h2>`など（他にも有り）に、classがついていないものは全体に影響が及びます。
このままマージしても影響がないのであれば、その旨のコメントをください。

**Comment by Kuma-inataku** [comment]
お疲れ様です。
こちらもCONTACTページと同様に、このままとさせていただきます。
