### ISSUE TITLE
404エラーの修正（contact）

### ISSUE THREAD

**Issue by Taka-hyt** [Kuma-inataku/tenkue-app-r005#8]
@Kuma-inataku 
contactページのメインビジュアルが404エラーになっているので修正をお願いします。
<img width="927" alt="スクリーンショット 2020-10-25 20 17 15" src="https://user-images.githubusercontent.com/53964838/97105598-71675100-16ff-11eb-8e6e-2554c3c93cd5.png">

**Comment by Kuma-inataku** [comment]
こちらも、他のページで検証ツールを使い参考にしつつimageのリンクを修正しました。

**Comment by Taka-hyt** [comment]
修正されたことを確認しました。
