### ISSUE TITLE
404エラーの修正（access）

### ISSUE THREAD

**Issue by Taka-hyt** [Kuma-inataku/tenkue-app-r005#9]
@Kuma-inataku 
accessページのメインビジュアルが404エラーになっているので修正をお願いします。
エラーになっているファイルも違うようです。
`access_01.jpg`が正ですね。
<img width="736" alt="スクリーンショット 2020-10-25 20 18 45" src="https://user-images.githubusercontent.com/53964838/97105676-21d55500-1700-11eb-9d1a-ca47042b5c87.png">

**Comment by Kuma-inataku** [comment]
他のページで検証ツールを使い参考にしつつimageのリンクを修正しました。

**Comment by Taka-hyt** [comment]
修正されたことを確認しました。
